In [1]:
import os
with open("./VOCdevkit/VOC2012/ImageSets/Main/train.txt") as read:
    xml_list = [os.path.join("./VOCdevkit/VOC2012/Annotations", line.strip() + ".xml")
    for line in read.readlines() if len(line.strip()) > 0]
print(xml_list)

['./VOCdevkit/VOC2012/Annotations\\2008_000008.xml', './VOCdevkit/VOC2012/Annotations\\2008_000015.xml', './VOCdevkit/VOC2012/Annotations\\2008_000019.xml', './VOCdevkit/VOC2012/Annotations\\2008_000023.xml', './VOCdevkit/VOC2012/Annotations\\2008_000028.xml', './VOCdevkit/VOC2012/Annotations\\2008_000033.xml', './VOCdevkit/VOC2012/Annotations\\2008_000036.xml', './VOCdevkit/VOC2012/Annotations\\2008_000037.xml', './VOCdevkit/VOC2012/Annotations\\2008_000041.xml', './VOCdevkit/VOC2012/Annotations\\2008_000045.xml', './VOCdevkit/VOC2012/Annotations\\2008_000053.xml', './VOCdevkit/VOC2012/Annotations\\2008_000060.xml', './VOCdevkit/VOC2012/Annotations\\2008_000066.xml', './VOCdevkit/VOC2012/Annotations\\2008_000070.xml', './VOCdevkit/VOC2012/Annotations\\2008_000074.xml', './VOCdevkit/VOC2012/Annotations\\2008_000085.xml', './VOCdevkit/VOC2012/Annotations\\2008_000089.xml', './VOCdevkit/VOC2012/Annotations\\2008_000093.xml', './VOCdevkit/VOC2012/Annotations\\2008_000095.xml', './VOCdevki

In [5]:
import torch

a = torch.as_tensor([1, 2, 3, 4])
print(a[:,3])

IndexError: too many indices for tensor of dimension 1

In [8]:
import torch
from torch import nn,optim,tensor
from torch.utils.data import DataLoader
from torchvision.datasets import ImageFolder
from torchvision.utils import  make_grid
from torchvision import datasets,transforms
ROOT_TRAIN = "E:/pytorch_net/AlexNet/data/train"
ROOT_TEST = 'E:/pytorch_net/AlexNet/data/val'

# 将图像的像素值归一化为-1 1之间
normalize = transforms.Normalize([0.5,0.5,0.5],[0.5,0.5,0.5])

# 改变图像的工具箱
train_transform = transforms.Compose([
    transforms.Resize((32,32)),
    transforms.RandomVerticalFlip(),
    transforms.ToTensor(),  # 转化为Tensor类型
    normalize
])

var_transform = transforms.Compose([
    transforms.Resize((32,32)),   # 根据数据集的大小改变
    transforms.ToTensor(),
    normalize
])

train_dataset = ImageFolder(ROOT_TRAIN,transform=train_transform)

test_dataset = ImageFolder(ROOT_TEST,transform = var_transform)

print(train_dataset)
print(test_dataset)
'''
#Dataloader(....)
dataset:就是pytorch已有的数据读取接口,或者自定义的数据接口的输出,该输出要么是torch.utils.data.Dataset类的对象,要么是继承自torch.utils.data.Dataset类的自定义类的对象

batch_size:如果有50000张训练集,则相当于把训练集平均分成(50000/batch_size)份,每份batch_size张图片
train_loader中的每个元素相当于一个分组,一个组中batch_size图片

shuffle:设置为True时会在每个epoch重新打乱数据(默认:False),一般在训练数据中会采用
num_workers:这个参数必须>=0,0的话表示数据导入在主进程中进行,其他大于0的数表示通过多个进程来导入数据,可以加快数据导入速度
drop_last:设定为True如果数据集大小不能被批量大小整除的时候,将丢到最后一个不完整的batch(默认为False)
'''

train_loader=DataLoader(train_dataset,batch_size=8,shuffle=True)
print(len(train_loader))
test_loader=DataLoader(test_dataset,batch_size=8,shuffle=False)
print(test_loader.size())

Dataset ImageFolder
    Number of datapoints: 19524
    Root location: E:/pytorch_net/AlexNet/data/train
    StandardTransform
Transform: Compose(
               Resize(size=(32, 32), interpolation=bilinear, max_size=None, antialias=None)
               RandomVerticalFlip(p=0.5)
               ToTensor()
               Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
           )
Dataset ImageFolder
    Number of datapoints: 4885
    Root location: E:/pytorch_net/AlexNet/data/val
    StandardTransform
Transform: Compose(
               Resize(size=(32, 32), interpolation=bilinear, max_size=None, antialias=None)
               ToTensor()
               Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
           )


AttributeError: 'DataLoader' object has no attribute 'size'

In [10]:
a = [1,2,3,4,5]
m,n = a[-2:]
print(m,n)

4 5


In [18]:
import torch

a = torch.rand((3, 4))
print(a)
print(a.unbind(1))
xmin, ymin, xmax, ymax = a.unbind(1)
print(xmin,ymin,xmax,ymax)
torch.stack((xmin,ymin,xmax,ymax),dim=1)

tensor([[0.0221, 0.0123, 0.8015, 0.6728],
        [0.0082, 0.2657, 0.9942, 0.6015],
        [0.5784, 0.0835, 0.5172, 0.4520]])
(tensor([0.0221, 0.0082, 0.5784]), tensor([0.0123, 0.2657, 0.0835]), tensor([0.8015, 0.9942, 0.5172]), tensor([0.6728, 0.6015, 0.4520]))
tensor([0.0221, 0.0082, 0.5784]) tensor([0.0123, 0.2657, 0.0835]) tensor([0.8015, 0.9942, 0.5172]) tensor([0.6728, 0.6015, 0.4520])


tensor([[0.0221, 0.0123, 0.8015, 0.6728],
        [0.0082, 0.2657, 0.9942, 0.6015],
        [0.5784, 0.0835, 0.5172, 0.4520]])

In [1]:
import torch
a = torch.Tensor([[2.0,3.0,3.3,9.0]])


In [2]:
print(([1] + [2, 3, 4]))

[1, 2, 3, 4]


In [3]:
import torch

print(torch.__version__)

1.12.1


In [4]:
a = [2,3,4]
print(a[0])

2


In [6]:
print(not isinstance([12, 23], (list, tuple)))

False
